---

- include: reset.yml
  when:
    - kubeadm_node_reset | default(false)

- include: install.yml

- include: preflight.yml

- include: init.yml
  when:
    - not hostvars['localhost']['_kubeadm_cluster_initialized'] | default(false)
    - kubeadm_node_role == "master"
    - ansible_play_hosts[0] == ansible_hostname

- include: generate-token.yml
  when:
    - hostvars['localhost']['_kubeadm_generate_token'] | default(false)
    - hostvars['localhost']['_kubeadm_ready_masters'][0] == ansible_hostname

- include: upload-certificates.yml
  when:
    - hostvars['localhost']['_kubeadm_upload_certificates'] | default(false)
    - hostvars['localhost']['_kubeadm_ready_masters'][0] == ansible_hostname

- include: join-master.yml
  when:
    - kubeadm_node_role == "master"
    - not _kubeadm_ready

- include: join-worker.yml
  when:
    - kubeadm_node_role == "worker"
    - not _kubeadm_ready
